import { groupByTheme, hasMoney } from "./theme.js";
import { cleanItem, formatDate } from "./clean.js";

const THEME_PREVIEW = 8; // items shown per theme before "show more"

// Render the issue archive as a single self-contained static page.
// Latest issue gets the full treatment (summary → themes → sources); older
// issues collapse into a compact archive list at the bottom.
export function renderSiteHtml(issues) {
  const [latest, ...older] = issues;
  const body = latest
    ? renderLatest(latest) + renderArchive(older)
    : `<p class="empty">No issues yet. Run <code>npm run scrape</code>.</p>`;

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>NorthSignal — Canadian AI policy &amp; funding tracker</title>
<style>${STYLE}</style>
</head>
<body>
<header class="masthead">
  <div class="brand">North<span>Signal</span></div>
  <p class="tagline">Canada's AI policy, funding &amp; RFP tracker — what changed, every issue.</p>
</header>
<main>
${body}
</main>
<footer class="foot">Generated by NorthSignal · sources are official Canadian gov &amp; institute pages</footer>
</body>
</html>
`;
}

function renderLatest(issue) {
  const items = collectItems(issue);
  const groups = groupByTheme(items);

  return `<section class="issue">
  <div class="issue-head">
    <span class="kicker">Latest issue</span>
    <h1>${esc(issue.date)}</h1>
    <div class="stats">
      ${stat(issue.counts.new, "new")}
      ${stat(issue.counts.changed, "updated")}
      ${stat(groups.length, "themes")}
      ${stat(activeSourceCount(issue), "sources")}
    </div>
  </div>
  ${items.length ? renderSummary(groups, items) : `<p class="empty">No changes this issue.</p>`}
  ${items.length ? renderThemes(groups) : ""}
  ${renderSources(issue)}
</section>`;
}

// --- Summary -------------------------------------------------------------
function renderSummary(groups, items) {
  const chips = groups
    .map((g) => `<a class="chip" href="#theme-${g.theme.key}">
        <span class="chip-icon">${g.theme.icon}</span>${esc(g.theme.label)}
        <span class="chip-count">${g.items.length}</span></a>`)
    .join("");

  const highlights = pickHighlights(items);
  const highlightHtml = highlights.length
    ? `<div class="highlights">
        <h3>Money on the move</h3>
        <ul class="cards">${highlights.map(highlightCard).join("")}</ul>
      </div>`
    : "";

  return `<section class="summary">
    <h2>Summary</h2>
    <div class="chips">${chips}</div>
    ${highlightHtml}
  </section>`;
}

// Recent + source-diverse: sort money items newest-first, max 2 per source.
function pickHighlights(items) {
  const money = items
    .filter(hasMoney)
    .sort((a, b) => (b.date ?? "").localeCompare(a.date ?? ""));
  const perSource = new Map();
  const out = [];
  for (const it of money) {
    const seen = perSource.get(it.source) ?? 0;
    if (seen >= 2) continue;
    perSource.set(it.source, seen + 1);
    out.push(it);
    if (out.length >= 6) break;
  }
  return out;
}

function highlightCard(item) {
  return `<li class="card">
    <a class="t" href="${esc(item.url)}">${esc(item.title)}</a>
    ${meta(item)}
  </li>`;
}

// --- Themes --------------------------------------------------------------
function renderThemes(groups) {
  const sections = groups.map(renderTheme).join("");
  return `<section class="themes"><h2>By theme</h2>${sections}</section>`;
}

function renderTheme(g) {
  const sorted = [...g.items].sort((a, b) => (b.date ?? "").localeCompare(a.date ?? ""));
  const head = sorted.slice(0, THEME_PREVIEW);
  const rest = sorted.slice(THEME_PREVIEW);
  const more = rest.length
    ? `<details class="more"><summary>${rest.length} more</summary>
        <ul class="items">${rest.map(itemRow).join("")}</ul></details>`
    : "";
  return `<div class="theme" id="theme-${g.theme.key}">
      <h3><span class="theme-icon">${g.theme.icon}</span>${esc(g.theme.label)}
        <span class="theme-count">${g.items.length}</span></h3>
      <ul class="items">${head.map(itemRow).join("")}</ul>
      ${more}
    </div>`;
}

function itemRow(item) {
  const tag = item.status === "updated" ? `<span class="tag upd">updated</span>` : "";
  return `<li>
    <a class="t" href="${esc(item.url)}">${tag}${esc(item.title)}</a>
    ${meta(item)}
  </li>`;
}

// Byline under a title: "date · source" (date omitted when unknown).
function meta(item) {
  const date = item.date
    ? `<span class="date">${esc(formatDate(item.date))}</span><span class="sep">·</span>`
    : "";
  return `<div class="m">${date}<span class="src">${esc(item.sourceName)}</span></div>`;
}

// --- Sources (reference appendix) ---------------------------------------
function renderSources(issue) {
  const rows = issue.perSource
    .map((s) => {
      if (s.error) {
        return `<li class="src-row err"><span>${esc(s.name)}</span><span>⚠️ ${esc(s.error)}</span></li>`;
      }
      const n = s.added.length + s.changed.length;
      const note = n ? `${n} new/updated` : "no change";
      return `<li class="src-row"><span>${esc(s.name)}</span><span class="src-note">${esc(note)}</span></li>`;
    })
    .join("");
  return `<section class="sources">
    <h2>Sources</h2>
    <ul class="src-list">${rows}</ul>
  </section>`;
}

// --- Archive of older issues --------------------------------------------
function renderArchive(older) {
  if (older.length === 0) return "";
  const rows = older
    .map(
      (i) => `<li><span class="arc-date">${esc(i.date)}</span>
      <span class="arc-counts">${i.counts.new} new · ${i.counts.changed} updated</span></li>`
    )
    .join("");
  return `<section class="archive"><h2>Past issues</h2><ul class="arc-list">${rows}</ul></section>`;
}

// --- helpers -------------------------------------------------------------
function collectItems(issue) {
  const items = [];
  for (const s of issue.perSource) {
    if (s.error) continue;
    for (const i of s.added) items.push({ ...cleanItem(i), sourceName: s.name, status: "new" });
    for (const i of s.changed) items.push({ ...cleanItem(i), sourceName: s.name, status: "updated" });
  }
  return items;
}

function activeSourceCount(issue) {
  return issue.perSource.filter((s) => !s.error).length;
}

function stat(value, label) {
  return `<div class="stat"><span class="num">${value}</span><span class="lbl">${esc(label)}</span></div>`;
}

function esc(s) {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

const STYLE = `
:root {
  --bg:#fbfaf8; --panel:#fff; --ink:#1c1b1a; --muted:#8a857c; --faint:#b3ada3;
  --line:#ebe6de; --accent:#b8351f; --accent-soft:#f6ece9; --chip:#f3f0ea;
}
@media (prefers-color-scheme: dark) {
  :root { --bg:#15130f; --panel:#1e1b16; --ink:#ece7de; --muted:#938c80; --faint:#6a6358;
          --line:#2b2720; --accent:#e8806f; --accent-soft:#2a201d; --chip:#241f19; }
}
* { box-sizing: border-box; }
body { margin:0; background:var(--bg); color:var(--ink);
  font:16px/1.6 ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  -webkit-font-smoothing:antialiased; }

/* masthead keeps the editorial serif accent */
.masthead { text-align:center; padding:2.5rem 1.25rem 1.5rem; border-bottom:1px solid var(--line); }
.brand { font:800 2.3rem/1 ui-sans-serif, -apple-system, sans-serif; letter-spacing:-.03em; }
.brand span { color:var(--accent); }
.tagline { color:var(--muted); margin:.55rem 0 0; font:italic 400 1rem/1.4 ui-serif, Georgia, serif; }

main { max-width:720px; margin:0 auto; padding:1.5rem 1.25rem 3rem; }

h1 { font:800 1.9rem/1.05 ui-sans-serif, sans-serif; margin:.25rem 0 1rem; letter-spacing:-.02em; }
h2 { font:600 .72rem/1 ui-sans-serif, sans-serif; text-transform:uppercase; letter-spacing:.14em;
  color:var(--muted); margin:2.75rem 0 1rem; padding-bottom:.5rem; border-bottom:1px solid var(--line); }
h3 { font:650 1.05rem/1.3 ui-sans-serif, sans-serif; margin:1.6rem 0 .5rem; }

a { color:inherit; text-decoration:none; }
a.t { color:var(--ink); }
a.t:hover { color:var(--accent); }

.kicker { font:600 .68rem/1 ui-sans-serif, sans-serif; text-transform:uppercase;
  letter-spacing:.16em; color:var(--accent); }
.stats { display:flex; gap:1.75rem; flex-wrap:wrap; margin:.5rem 0 0; }
.stat { display:flex; flex-direction:column; gap:.15rem; }
.stat .num { font:750 1.7rem/1 ui-sans-serif, sans-serif; letter-spacing:-.02em; }
.stat .lbl { font-size:.7rem; text-transform:uppercase; letter-spacing:.1em; color:var(--muted); }

/* summary chips */
.chips { display:flex; flex-wrap:wrap; gap:.45rem; }
.chip { display:inline-flex; align-items:center; gap:.4rem; padding:.32rem .7rem;
  background:var(--chip); border:1px solid var(--line); border-radius:999px;
  font:500 .82rem/1 ui-sans-serif, sans-serif; color:var(--ink); transition:border-color .12s; }
.chip:hover { border-color:var(--accent); }
.chip-icon { font-size:.95rem; }
.chip-count { color:var(--accent); font-weight:700; font-size:.78rem; }

/* highlight cards */
.highlights { margin-top:1.75rem; }
.highlights h3 { display:flex; align-items:center; gap:.4rem; font-size:.95rem; margin:0 0 .7rem; }
.highlights h3::before { content:"●"; color:var(--accent); font-size:.6rem; }
ul.cards { list-style:none; margin:0; padding:0; display:grid;
  grid-template-columns:repeat(auto-fill, minmax(215px,1fr)); gap:.6rem; }
.card { background:var(--panel); border:1px solid var(--line); border-radius:.6rem;
  padding:.75rem .85rem; display:flex; flex-direction:column; gap:.5rem; }
.card .t { font:600 .92rem/1.35 ui-sans-serif, sans-serif;
  display:-webkit-box; -webkit-line-clamp:3; -webkit-box-orient:vertical; overflow:hidden; }

/* item rows */
ul.items { list-style:none; margin:0; padding:0; }
ul.items > li { padding:.6rem 0; border-bottom:1px solid var(--line); }
ul.items .t { font:500 1rem/1.4 ui-sans-serif, sans-serif; }
.m { display:flex; align-items:baseline; flex-wrap:wrap; gap:.4rem; margin-top:.3rem;
  font:.76rem/1.3 ui-sans-serif, sans-serif; }
.date { color:var(--accent); font-weight:600; white-space:nowrap; }
.sep { color:var(--faint); }
.src { color:var(--muted); }
.tag { font:700 .6rem/1 ui-sans-serif, sans-serif; text-transform:uppercase; letter-spacing:.05em;
  background:#9a6700; color:#fff; padding:.12rem .35rem; border-radius:.25rem; margin-right:.4rem;
  vertical-align:.05em; }

.theme { margin-bottom:.5rem; }
.theme h3 { display:flex; align-items:center; gap:.5rem; }
.theme-icon { font-size:1.15rem; }
.theme-count { margin-left:auto; font:600 .75rem/1 ui-sans-serif, sans-serif; color:var(--muted);
  background:var(--chip); border:1px solid var(--line); border-radius:999px; padding:.12rem .5rem; }
.more { margin:.5rem 0 0; }
.more summary { cursor:pointer; color:var(--accent); font:600 .82rem/1 ui-sans-serif, sans-serif;
  padding:.4rem 0; list-style:none; }
.more summary::-webkit-details-marker { display:none; }
.more summary::before { content:"▸ "; }
.more[open] summary::before { content:"▾ "; }

/* sources + archive */
.src-list, .arc-list { list-style:none; margin:0; padding:0; }
.src-row, .arc-list li { display:flex; justify-content:space-between; gap:1rem; padding:.55rem 0;
  border-bottom:1px solid var(--line); font:.88rem/1.4 ui-sans-serif, sans-serif; }
.src-note, .arc-counts { color:var(--muted); }
.src-row.err { color:var(--accent); }
.empty { color:var(--muted); }
.foot { text-align:center; color:var(--faint); font:.76rem/1.5 ui-sans-serif, sans-serif;
  padding:2rem 1.25rem; border-top:1px solid var(--line); }
`;
